import { Noto_Serif_KR } from "next/font/google";
import "./globals.css";

const notoSerifKr = Noto_Serif_KR({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-noto-serif-kr",
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSerifKr.variable} antialiased`}>{children}</body>
    </html>
  );
}
